# This code defines a VGT class with methods for starting Docker services, 
# connecting to Elasticsearch, reading search terms from a file, and returning the image path. 
# The main function initializes the VGT class, starts Docker services, connects to Elasticsearch, 
# and then enters a while loop to process user input for returning image paths. 
# The loop continues until the user types 'exit'.


import pandas as pd
from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk
import json

import time
import subprocess
from random import randint

class VGT:
    def __init__(self):
        self.client = None

    # Start Docker using compose.yaml
    def start_docker_services(self) -> None:
        command = ["docker", "compose", "up", "--build", "-d"]
        try:
            subprocess.run(command, check=True)
            print("Docker Compose up --build executed successfully! Waiting for services to start...")
            time.sleep(40)  # Wait for services to initialize
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to start Docker services: {e}")

    # Connect to Elasticsearch
    def connect_to_elasticSearch(self): 
        self.client = Elasticsearch("http://localhost:9200/")
        if not self.client.ping():
            print("Elasticsearch connection failed.")
            exit()

        # Load the CSV file into a pandas DataFrame
        csv_file = "./csv/images_path.csv"
        df = pd.read_csv(csv_file, delimiter=";")

        # Define the index name
        index_name = "images"  # Replace with your desired index name

        # Convert DataFrame to a list of dictionaries
        records = df.to_dict(orient="records")

        # Prepare the data for bulk upload
        actions = [
            {
                "_index": index_name,
                "_source": record
            }
            for record in records
        ]

        # Create the index and upload data
        try:
            # Create index if it doesn't exist
            if not self.client.indices.exists(index=index_name):
                self.client.indices.create(index=index_name)

            # Bulk upload
            bulk(self.client, actions)
        except Exception as e:
            print(f"An error occurred: {e}")

    # Read search terms from file
    def read_search_terms_from_file(self, filename):
        try:
            with open(filename, 'r') as file:
                data = json.load(file)
                search_terms = " ".join([entry["text"] for entry in data])
                continent = data[0]["continent"]
            return search_terms, continent
        except FileNotFoundError:
            print(f"Error: The file {filename} does not exist.")
            return None

    # Return image path
    def return_image_path(self, input_file):
        # The output file where image path will be written
        file_with_path = "./assets/resources/Text/textFile01.json"
        text_file = "./assets/resources/Text/textFile01.txt"

        search_terms, continent = self.read_search_terms_from_file(input_file)

        if search_terms == "random":
            try:
                query = {
                    "query": {
                        "bool": {
                            "must": [
                                {
                                    "term": {
                                        "continent.keyword": continent
                                    }
                                }
                            ]
                        }
                    },
                    "size": 100,  # estimation of the maximum nr of images we will have pregenerated by continent
                    "sort": [
                        {"_score": {"order": "desc"}},
                    ]
                }
            except Exception as e:
                print(f"Error during Elasticsearch search: {e}")

            # Perform the search
            response = self.client.search(index="images", body=query)

            # Choose random image from the found images
            r = randint(0, len(response["hits"]["hits"]) - 1)
            result = response["hits"]["hits"][r]

        if search_terms != "random":
            query = {
                "query": {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "continent.keyword": continent
                                }
                            },
                            {
                                "multi_match": {
                                    "query": search_terms,
                                    "fields": ["title", "content", "tags"],
                                    "fuzziness": 2
                                }
                            }
                        ]
                    }
                },
                "size": 1,
                "sort": [
                    {"_score": {"order": "desc"}},
                ]
            }
            # Perform the search
            response = self.client.search(index="images", body=query)

            if len(response["hits"]["hits"]) > 0:
                result = response["hits"]["hits"][0]
            else:
                result = {"_id": "None", "_source": {"title": "None", 
                                                     "image_path": "None", 
                                                     "tags": "None", 
                                                     "content": "None"},
                                                     "_score": 0}

        print(result["_source"]["title"])

        # Write the result to the output file
        with open(file_with_path, "r") as f:
            transcriptions = json.load(f)

        for transcription in transcriptions:
            transcription.update({
                "text": search_terms,
                "continent": continent,
                "ID": result["_id"],
                "Title": result["_source"]["title"],
                "Relevance": result["_score"],
                "Image Path": result["_source"]["image_path"],
                "Tags": result["_source"]["tags"],
                "Content": result["_source"]["content"]
            })

        with open(file_with_path, "w") as f:
            json.dump(transcriptions, f, indent=4)

        image_path = result["_source"]["image_path"]
        with open(text_file, "w") as t:
            t.write(image_path)

# def main():
#     vgt = VGT()
#     vgt.start_docker_services()
#     vgt.connect_to_elasticSearch()

#     while True:
#         input_file = input("Enter the input file path (or type 'exit' to stop): ")
#         if input_file.lower() == 'exit':
#             break
#         vgt.return_image_path(input_file)

# if __name__ == "__main__":
#     main()
