import pandas as pd
from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk
import json
import speech_recognition as sr
import time as time
import subprocess
from random import randint

# Connect to Elasticsearch
def connect_to_elasticSearch(): 
    client = Elasticsearch("http://localhost:9200/")

    if not client.ping():
        print("Elasticsearch connection failed.")
        exit()

    print("Connected to Elasticsearch!")

    # Load the CSV file into a pandas DataFrame
    csv_file =   "./images_path.csv"
    df = pd.read_csv(csv_file, delimiter=";")

    # Define the index name
    index_name = "images"  # Replace with your desired index name

    # Convert DataFrame to a list of dictionaries
    records = df.to_dict(orient="records")

    # Prepare the data for bulk upload
    actions = [
        {
            "_index": index_name,
            "_source": record
        }
        for record in records
    ]

    # Create the index and upload data
    try:
        # Create index if it doesn't exist
        if not client.indices.exists(index=index_name):
            client.indices.create(index=index_name)

        # Bulk upload
        bulk(client, actions)
        print(f"Data from {csv_file} uploaded successfully to index '{index_name}'!")
    except Exception as e:
        print(f"An error occurred: {e}")
    
    return client

def read_search_terms_from_file(filename):
    try:
        with open(filename, 'r') as file:
            data = json.load(file)
            
            search_terms = " ".join([entry["text"] for entry in data])
            continent = data[0]["continent"]

        return search_terms, continent
    
    except FileNotFoundError:
        print(f"Error: The file {filename} does not exist.")
        return None

def return_image_path(input_file):

    # the output file where image path will be written: 
    file_with_path = "./assets/resources/Text/textFile01.json"

    es = connect_to_elasticSearch()
    
    search_terms, continent = read_search_terms_from_file(input_file)
    print("SEARCH FOR THIS ", search_terms, "in continent:", continent)


    if search_terms == "random":
        try:
            query = {
                "query": {
                    "bool": {
                        "must": [
                            {
                                "term": {
                                    "continent.keyword": continent
                                }
                            }
                        ]
                    }
                },
                "size": 100,  # estimation of the maximum nr of images we will have pregenerated by continent
                "sort": [
                    {"_score": {"order": "desc"}},
                ]
            }
        
        except Exception as e:
            print(f"Error during Elasticsearch search: {e}")


        # Perform the search
        response = es.search(index="images", body=query)

        # chose random image from the found images
        r = randint(0, len(response["hits"]["hits"])-1)
        random_result = response["hits"]["hits"][r]

        # write the result to the output file


        with open(file_with_path, "r") as f:
            transcriptions = json.load(f)

        for transcription in transcriptions:
            transcription.update({
                "text" : "random image of chosen continent",
                "continent" : continent,
                "ID": random_result["_id"],
                "Title": random_result["_source"]["title"],
                "Relevance": random_result["_score"],
                "Image Path": random_result["_source"]["image_path"]
            })

        with open(file_with_path, "w") as f:
            json.dump(transcriptions, f, indent=4)
            f.close()


    if search_terms != "random":
        try:  
    
            query = {
                        
                        "query": 
                        {
                            "bool": 
                            {
                                "must": 
                                [
                                    {
                                        "term": {
                                            "continent.keyword": continent
                                        }
                                    },
                                    {
                                        "multi_match": 
                                        {
                                            "query": search_terms,
                                            "fields": ["title", "content", "tags"]
                                        }
                                    }
                                ]
                            }
                        },
                        "size": 100, 
                        
                        "sort": [
                            {"_score": {"order": "desc"}}
                        ]
                        
                        

                    }
        except Exception as e:
            print(f"Error during Elasticsearch search: {e}")
        
        # Perform the search
        response = es.search(index="images", body=query)


        found_im = {}
        if response["hits"]["hits"]:
            print(f"Found {len(response['hits']['hits'])} result(s):")
            results = response["hits"]["hits"]
            for result in results:
                print(f"ID: {result['_id']}")
                print(f"Title: {result['_source']['title']}")
                print(f"Tags: {result['_source']['tags']}")
                print(f"Content: {result['_source']['content']}")
                print(f"Relevance Score: {result['_score']}")
                print(f"Image Path: {result['_source']['image_path']}\n")
             
                found_im[result['_source']['title']] = [result['_score'],
                                                        result['_id'],
                                                        str(result['_source']['image_path']),
                                                        result['_source']['tags'],
                                                        str(result['_source']['content'])]
                print("found_im", found_im)

                

            with open(file_with_path, "r") as f:
                transcriptions = json.load(f)

            for transcription in transcriptions:
                transcription.update({
                    "text" : search_terms,
                    "continent" : continent,
                    "ID": result["_id"],
                    "Title": result["_source"]["title"],
                    "Relevance": result["_score"],
                    "Image Path": result["_source"]["image_path"],
                    "Tags (for testing)": result["_source"]["tags"],
                    "Content (for testing)": result["_source"]["content"]


                })

            with open(file_with_path, "w") as f:
                json.dump(transcriptions, f, indent=4)
    else:
        print("No results found.")
        

return_image_path(input_file="./search_image.json")